version: "3.3"
services:
  integralces-demo:
    build: .
    restart: unless-stopped
    ports: 
      - 2029:2029
    volumes:
      - type: bind
        source: /opt/ices
        target: /var/www/html/sites/all/modules/ices
    environment:
      - NOTIFICATIONS_CLIENT_ID=notifications.test.komunitin.org
      - NOTIFICATIONS_CLIENT_SECRET=${NOTIFICATIONS_CLIENT_SECRET}
      - NOTIFICATIONS_API_URL=https://notifications.test.komunitin.org
      - CES_USER_GOOGLE_MAPS_KEY=${CES_USER_GOOGLE_MAPS_KEY}
      - NOTIFICATIONS_EVENTS_USERNAME=integralces
      - NOTIFICATIONS_EVENTS_PASSWORD=${NOTIFICATIONS_CLIENT_SECRET}
