version: "3.3"
services:
  integralces-demo:
    build: .
    restart: unless-stopped
    ports: 
      - 2029:2029
    volumes:
      - type: bind
        source: /opt/ices
        target: /var/www/html/sites/all/modules/ices
